// Generated by gencpp from file nist_gear/ConveyorBeltControlResponse.msg
// DO NOT EDIT!


#ifndef NIST_GEAR_MESSAGE_CONVEYORBELTCONTROLRESPONSE_H
#define NIST_GEAR_MESSAGE_CONVEYORBELTCONTROLRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nist_gear
{
template <class ContainerAllocator>
struct ConveyorBeltControlResponse_
{
  typedef ConveyorBeltControlResponse_<ContainerAllocator> Type;

  ConveyorBeltControlResponse_()
    : success(false)  {
    }
  ConveyorBeltControlResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::nist_gear::ConveyorBeltControlResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nist_gear::ConveyorBeltControlResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ConveyorBeltControlResponse_

typedef ::nist_gear::ConveyorBeltControlResponse_<std::allocator<void> > ConveyorBeltControlResponse;

typedef boost::shared_ptr< ::nist_gear::ConveyorBeltControlResponse > ConveyorBeltControlResponsePtr;
typedef boost::shared_ptr< ::nist_gear::ConveyorBeltControlResponse const> ConveyorBeltControlResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nist_gear::ConveyorBeltControlResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nist_gear::ConveyorBeltControlResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nist_gear::ConveyorBeltControlResponse_<ContainerAllocator1> & lhs, const ::nist_gear::ConveyorBeltControlResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nist_gear::ConveyorBeltControlResponse_<ContainerAllocator1> & lhs, const ::nist_gear::ConveyorBeltControlResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nist_gear

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::nist_gear::ConveyorBeltControlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nist_gear::ConveyorBeltControlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nist_gear::ConveyorBeltControlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nist_gear::ConveyorBeltControlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nist_gear::ConveyorBeltControlResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nist_gear::ConveyorBeltControlResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nist_gear::ConveyorBeltControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::nist_gear::ConveyorBeltControlResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::nist_gear::ConveyorBeltControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nist_gear/ConveyorBeltControlResponse";
  }

  static const char* value(const ::nist_gear::ConveyorBeltControlResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nist_gear::ConveyorBeltControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"\n"
;
  }

  static const char* value(const ::nist_gear::ConveyorBeltControlResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nist_gear::ConveyorBeltControlResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConveyorBeltControlResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nist_gear::ConveyorBeltControlResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nist_gear::ConveyorBeltControlResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIST_GEAR_MESSAGE_CONVEYORBELTCONTROLRESPONSE_H
