// Generated by gencpp from file nist_gear/ConveyorBeltControl.msg
// DO NOT EDIT!


#ifndef NIST_GEAR_MESSAGE_CONVEYORBELTCONTROL_H
#define NIST_GEAR_MESSAGE_CONVEYORBELTCONTROL_H

#include <ros/service_traits.h>


#include <nist_gear/ConveyorBeltControlRequest.h>
#include <nist_gear/ConveyorBeltControlResponse.h>


namespace nist_gear
{

struct ConveyorBeltControl
{

typedef ConveyorBeltControlRequest Request;
typedef ConveyorBeltControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ConveyorBeltControl
} // namespace nist_gear


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nist_gear::ConveyorBeltControl > {
  static const char* value()
  {
    return "8b0e8e2d213d4fc4d0fcb5152aec2d9d";
  }

  static const char* value(const ::nist_gear::ConveyorBeltControl&) { return value(); }
};

template<>
struct DataType< ::nist_gear::ConveyorBeltControl > {
  static const char* value()
  {
    return "nist_gear/ConveyorBeltControl";
  }

  static const char* value(const ::nist_gear::ConveyorBeltControl&) { return value(); }
};


// service_traits::MD5Sum< ::nist_gear::ConveyorBeltControlRequest> should match
// service_traits::MD5Sum< ::nist_gear::ConveyorBeltControl >
template<>
struct MD5Sum< ::nist_gear::ConveyorBeltControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nist_gear::ConveyorBeltControl >::value();
  }
  static const char* value(const ::nist_gear::ConveyorBeltControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nist_gear::ConveyorBeltControlRequest> should match
// service_traits::DataType< ::nist_gear::ConveyorBeltControl >
template<>
struct DataType< ::nist_gear::ConveyorBeltControlRequest>
{
  static const char* value()
  {
    return DataType< ::nist_gear::ConveyorBeltControl >::value();
  }
  static const char* value(const ::nist_gear::ConveyorBeltControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nist_gear::ConveyorBeltControlResponse> should match
// service_traits::MD5Sum< ::nist_gear::ConveyorBeltControl >
template<>
struct MD5Sum< ::nist_gear::ConveyorBeltControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nist_gear::ConveyorBeltControl >::value();
  }
  static const char* value(const ::nist_gear::ConveyorBeltControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nist_gear::ConveyorBeltControlResponse> should match
// service_traits::DataType< ::nist_gear::ConveyorBeltControl >
template<>
struct DataType< ::nist_gear::ConveyorBeltControlResponse>
{
  static const char* value()
  {
    return DataType< ::nist_gear::ConveyorBeltControl >::value();
  }
  static const char* value(const ::nist_gear::ConveyorBeltControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NIST_GEAR_MESSAGE_CONVEYORBELTCONTROL_H
