// Generated by gencpp from file nist_gear/DetectedProduct.msg
// DO NOT EDIT!


#ifndef NIST_GEAR_MESSAGE_DETECTEDPRODUCT_H
#define NIST_GEAR_MESSAGE_DETECTEDPRODUCT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace nist_gear
{
template <class ContainerAllocator>
struct DetectedProduct_
{
  typedef DetectedProduct_<ContainerAllocator> Type;

  DetectedProduct_()
    : type()
    , is_faulty(false)
    , pose()  {
    }
  DetectedProduct_(const ContainerAllocator& _alloc)
    : type(_alloc)
    , is_faulty(false)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _type_type;
  _type_type type;

   typedef uint8_t _is_faulty_type;
  _is_faulty_type is_faulty;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::nist_gear::DetectedProduct_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nist_gear::DetectedProduct_<ContainerAllocator> const> ConstPtr;

}; // struct DetectedProduct_

typedef ::nist_gear::DetectedProduct_<std::allocator<void> > DetectedProduct;

typedef boost::shared_ptr< ::nist_gear::DetectedProduct > DetectedProductPtr;
typedef boost::shared_ptr< ::nist_gear::DetectedProduct const> DetectedProductConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nist_gear::DetectedProduct_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nist_gear::DetectedProduct_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nist_gear::DetectedProduct_<ContainerAllocator1> & lhs, const ::nist_gear::DetectedProduct_<ContainerAllocator2> & rhs)
{
  return lhs.type == rhs.type &&
    lhs.is_faulty == rhs.is_faulty &&
    lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nist_gear::DetectedProduct_<ContainerAllocator1> & lhs, const ::nist_gear::DetectedProduct_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nist_gear

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::nist_gear::DetectedProduct_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nist_gear::DetectedProduct_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nist_gear::DetectedProduct_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nist_gear::DetectedProduct_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nist_gear::DetectedProduct_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nist_gear::DetectedProduct_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nist_gear::DetectedProduct_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c1078dfbc537fe0a742246656582af4f";
  }

  static const char* value(const ::nist_gear::DetectedProduct_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc1078dfbc537fe0aULL;
  static const uint64_t static_value2 = 0x742246656582af4fULL;
};

template<class ContainerAllocator>
struct DataType< ::nist_gear::DetectedProduct_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nist_gear/DetectedProduct";
  }

  static const char* value(const ::nist_gear::DetectedProduct_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nist_gear::DetectedProduct_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# DetectedProduct message\n"
"# This structure contains the information of a detected product.\n"
"\n"
"# Product type\n"
"string type\n"
"\n"
"# Whether or not the product is faulty\n"
"bool is_faulty\n"
"\n"
"# Target pose\n"
"geometry_msgs/Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::nist_gear::DetectedProduct_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nist_gear::DetectedProduct_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
      stream.next(m.is_faulty);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DetectedProduct_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nist_gear::DetectedProduct_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nist_gear::DetectedProduct_<ContainerAllocator>& v)
  {
    s << indent << "type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.type);
    s << indent << "is_faulty: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_faulty);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIST_GEAR_MESSAGE_DETECTEDPRODUCT_H
