// Generated by gencpp from file nist_gear/DetectedShipment.msg
// DO NOT EDIT!


#ifndef NIST_GEAR_MESSAGE_DETECTEDSHIPMENT_H
#define NIST_GEAR_MESSAGE_DETECTEDSHIPMENT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <nist_gear/DetectedProduct.h>

namespace nist_gear
{
template <class ContainerAllocator>
struct DetectedShipment_
{
  typedef DetectedShipment_<ContainerAllocator> Type;

  DetectedShipment_()
    : destination_id()
    , products()  {
    }
  DetectedShipment_(const ContainerAllocator& _alloc)
    : destination_id(_alloc)
    , products(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _destination_id_type;
  _destination_id_type destination_id;

   typedef std::vector< ::nist_gear::DetectedProduct_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::nist_gear::DetectedProduct_<ContainerAllocator> >::other >  _products_type;
  _products_type products;





  typedef boost::shared_ptr< ::nist_gear::DetectedShipment_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nist_gear::DetectedShipment_<ContainerAllocator> const> ConstPtr;

}; // struct DetectedShipment_

typedef ::nist_gear::DetectedShipment_<std::allocator<void> > DetectedShipment;

typedef boost::shared_ptr< ::nist_gear::DetectedShipment > DetectedShipmentPtr;
typedef boost::shared_ptr< ::nist_gear::DetectedShipment const> DetectedShipmentConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nist_gear::DetectedShipment_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nist_gear::DetectedShipment_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nist_gear::DetectedShipment_<ContainerAllocator1> & lhs, const ::nist_gear::DetectedShipment_<ContainerAllocator2> & rhs)
{
  return lhs.destination_id == rhs.destination_id &&
    lhs.products == rhs.products;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nist_gear::DetectedShipment_<ContainerAllocator1> & lhs, const ::nist_gear::DetectedShipment_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nist_gear

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::nist_gear::DetectedShipment_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nist_gear::DetectedShipment_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nist_gear::DetectedShipment_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nist_gear::DetectedShipment_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nist_gear::DetectedShipment_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nist_gear::DetectedShipment_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nist_gear::DetectedShipment_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aa636304139751ae787eeb3a3793e615";
  }

  static const char* value(const ::nist_gear::DetectedShipment_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaa636304139751aeULL;
  static const uint64_t static_value2 = 0x787eeb3a3793e615ULL;
};

template<class ContainerAllocator>
struct DataType< ::nist_gear::DetectedShipment_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nist_gear/DetectedShipment";
  }

  static const char* value(const ::nist_gear::DetectedShipment_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nist_gear::DetectedShipment_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Shipment contents message\n"
"# This structure contains the information about a shipment being submitted\n"
"\n"
"# The ID of the shipping_box or tray the shipment was detected in\n"
"string destination_id\n"
"\n"
"# Collection of products\n"
"DetectedProduct[] products\n"
"\n"
"================================================================================\n"
"MSG: nist_gear/DetectedProduct\n"
"# DetectedProduct message\n"
"# This structure contains the information of a detected product.\n"
"\n"
"# Product type\n"
"string type\n"
"\n"
"# Whether or not the product is faulty\n"
"bool is_faulty\n"
"\n"
"# Target pose\n"
"geometry_msgs/Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::nist_gear::DetectedShipment_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nist_gear::DetectedShipment_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.destination_id);
      stream.next(m.products);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DetectedShipment_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nist_gear::DetectedShipment_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nist_gear::DetectedShipment_<ContainerAllocator>& v)
  {
    s << indent << "destination_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.destination_id);
    s << indent << "products[]" << std::endl;
    for (size_t i = 0; i < v.products.size(); ++i)
    {
      s << indent << "  products[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::nist_gear::DetectedProduct_<ContainerAllocator> >::stream(s, indent + "    ", v.products[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIST_GEAR_MESSAGE_DETECTEDSHIPMENT_H
