// Generated by gencpp from file nist_gear/DetectShipment.msg
// DO NOT EDIT!


#ifndef NIST_GEAR_MESSAGE_DETECTSHIPMENT_H
#define NIST_GEAR_MESSAGE_DETECTSHIPMENT_H

#include <ros/service_traits.h>


#include <nist_gear/DetectShipmentRequest.h>
#include <nist_gear/DetectShipmentResponse.h>


namespace nist_gear
{

struct DetectShipment
{

typedef DetectShipmentRequest Request;
typedef DetectShipmentResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DetectShipment
} // namespace nist_gear


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nist_gear::DetectShipment > {
  static const char* value()
  {
    return "f1cde41b69fdae4a3f7f6ab4fbc94332";
  }

  static const char* value(const ::nist_gear::DetectShipment&) { return value(); }
};

template<>
struct DataType< ::nist_gear::DetectShipment > {
  static const char* value()
  {
    return "nist_gear/DetectShipment";
  }

  static const char* value(const ::nist_gear::DetectShipment&) { return value(); }
};


// service_traits::MD5Sum< ::nist_gear::DetectShipmentRequest> should match
// service_traits::MD5Sum< ::nist_gear::DetectShipment >
template<>
struct MD5Sum< ::nist_gear::DetectShipmentRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nist_gear::DetectShipment >::value();
  }
  static const char* value(const ::nist_gear::DetectShipmentRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nist_gear::DetectShipmentRequest> should match
// service_traits::DataType< ::nist_gear::DetectShipment >
template<>
struct DataType< ::nist_gear::DetectShipmentRequest>
{
  static const char* value()
  {
    return DataType< ::nist_gear::DetectShipment >::value();
  }
  static const char* value(const ::nist_gear::DetectShipmentRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nist_gear::DetectShipmentResponse> should match
// service_traits::MD5Sum< ::nist_gear::DetectShipment >
template<>
struct MD5Sum< ::nist_gear::DetectShipmentResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nist_gear::DetectShipment >::value();
  }
  static const char* value(const ::nist_gear::DetectShipmentResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nist_gear::DetectShipmentResponse> should match
// service_traits::DataType< ::nist_gear::DetectShipment >
template<>
struct DataType< ::nist_gear::DetectShipmentResponse>
{
  static const char* value()
  {
    return DataType< ::nist_gear::DetectShipment >::value();
  }
  static const char* value(const ::nist_gear::DetectShipmentResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NIST_GEAR_MESSAGE_DETECTSHIPMENT_H
