// Generated by gencpp from file nist_gear/DroneControlRequest.msg
// DO NOT EDIT!


#ifndef NIST_GEAR_MESSAGE_DRONECONTROLREQUEST_H
#define NIST_GEAR_MESSAGE_DRONECONTROLREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nist_gear
{
template <class ContainerAllocator>
struct DroneControlRequest_
{
  typedef DroneControlRequest_<ContainerAllocator> Type;

  DroneControlRequest_()
    : shipment_type()  {
    }
  DroneControlRequest_(const ContainerAllocator& _alloc)
    : shipment_type(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _shipment_type_type;
  _shipment_type_type shipment_type;





  typedef boost::shared_ptr< ::nist_gear::DroneControlRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nist_gear::DroneControlRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DroneControlRequest_

typedef ::nist_gear::DroneControlRequest_<std::allocator<void> > DroneControlRequest;

typedef boost::shared_ptr< ::nist_gear::DroneControlRequest > DroneControlRequestPtr;
typedef boost::shared_ptr< ::nist_gear::DroneControlRequest const> DroneControlRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nist_gear::DroneControlRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nist_gear::DroneControlRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nist_gear::DroneControlRequest_<ContainerAllocator1> & lhs, const ::nist_gear::DroneControlRequest_<ContainerAllocator2> & rhs)
{
  return lhs.shipment_type == rhs.shipment_type;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nist_gear::DroneControlRequest_<ContainerAllocator1> & lhs, const ::nist_gear::DroneControlRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nist_gear

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::nist_gear::DroneControlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nist_gear::DroneControlRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nist_gear::DroneControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nist_gear::DroneControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nist_gear::DroneControlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nist_gear::DroneControlRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nist_gear::DroneControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3cb3e9e27775802f44b63ca135bf6dec";
  }

  static const char* value(const ::nist_gear::DroneControlRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3cb3e9e27775802fULL;
  static const uint64_t static_value2 = 0x44b63ca135bf6decULL;
};

template<class ContainerAllocator>
struct DataType< ::nist_gear::DroneControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nist_gear/DroneControlRequest";
  }

  static const char* value(const ::nist_gear::DroneControlRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nist_gear::DroneControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Drone Control\n"
"\n"
"string shipment_type\n"
"\n"
;
  }

  static const char* value(const ::nist_gear::DroneControlRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nist_gear::DroneControlRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.shipment_type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DroneControlRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nist_gear::DroneControlRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nist_gear::DroneControlRequest_<ContainerAllocator>& v)
  {
    s << indent << "shipment_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.shipment_type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIST_GEAR_MESSAGE_DRONECONTROLREQUEST_H
