// Generated by gencpp from file nist_gear/GetMaterialLocationsRequest.msg
// DO NOT EDIT!


#ifndef NIST_GEAR_MESSAGE_GETMATERIALLOCATIONSREQUEST_H
#define NIST_GEAR_MESSAGE_GETMATERIALLOCATIONSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nist_gear
{
template <class ContainerAllocator>
struct GetMaterialLocationsRequest_
{
  typedef GetMaterialLocationsRequest_<ContainerAllocator> Type;

  GetMaterialLocationsRequest_()
    : material_type()  {
    }
  GetMaterialLocationsRequest_(const ContainerAllocator& _alloc)
    : material_type(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _material_type_type;
  _material_type_type material_type;





  typedef boost::shared_ptr< ::nist_gear::GetMaterialLocationsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nist_gear::GetMaterialLocationsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetMaterialLocationsRequest_

typedef ::nist_gear::GetMaterialLocationsRequest_<std::allocator<void> > GetMaterialLocationsRequest;

typedef boost::shared_ptr< ::nist_gear::GetMaterialLocationsRequest > GetMaterialLocationsRequestPtr;
typedef boost::shared_ptr< ::nist_gear::GetMaterialLocationsRequest const> GetMaterialLocationsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nist_gear::GetMaterialLocationsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nist_gear::GetMaterialLocationsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nist_gear::GetMaterialLocationsRequest_<ContainerAllocator1> & lhs, const ::nist_gear::GetMaterialLocationsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.material_type == rhs.material_type;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nist_gear::GetMaterialLocationsRequest_<ContainerAllocator1> & lhs, const ::nist_gear::GetMaterialLocationsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nist_gear

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::nist_gear::GetMaterialLocationsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nist_gear::GetMaterialLocationsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nist_gear::GetMaterialLocationsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nist_gear::GetMaterialLocationsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nist_gear::GetMaterialLocationsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nist_gear::GetMaterialLocationsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nist_gear::GetMaterialLocationsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f0792282be4b01a1cf5b25de45b5326c";
  }

  static const char* value(const ::nist_gear::GetMaterialLocationsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf0792282be4b01a1ULL;
  static const uint64_t static_value2 = 0xcf5b25de45b5326cULL;
};

template<class ContainerAllocator>
struct DataType< ::nist_gear::GetMaterialLocationsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nist_gear/GetMaterialLocationsRequest";
  }

  static const char* value(const ::nist_gear::GetMaterialLocationsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nist_gear::GetMaterialLocationsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Query storage locations for a particular material type.\n"
"\n"
"string material_type  # the type of material for which to query locations\n"
"\n"
;
  }

  static const char* value(const ::nist_gear::GetMaterialLocationsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nist_gear::GetMaterialLocationsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.material_type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetMaterialLocationsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nist_gear::GetMaterialLocationsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nist_gear::GetMaterialLocationsRequest_<ContainerAllocator>& v)
  {
    s << indent << "material_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.material_type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIST_GEAR_MESSAGE_GETMATERIALLOCATIONSREQUEST_H
