// Generated by gencpp from file nist_gear/GetMaterialLocations.msg
// DO NOT EDIT!


#ifndef NIST_GEAR_MESSAGE_GETMATERIALLOCATIONS_H
#define NIST_GEAR_MESSAGE_GETMATERIALLOCATIONS_H

#include <ros/service_traits.h>


#include <nist_gear/GetMaterialLocationsRequest.h>
#include <nist_gear/GetMaterialLocationsResponse.h>


namespace nist_gear
{

struct GetMaterialLocations
{

typedef GetMaterialLocationsRequest Request;
typedef GetMaterialLocationsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetMaterialLocations
} // namespace nist_gear


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nist_gear::GetMaterialLocations > {
  static const char* value()
  {
    return "cbf263a50360138b80b1bdd46f5ff56f";
  }

  static const char* value(const ::nist_gear::GetMaterialLocations&) { return value(); }
};

template<>
struct DataType< ::nist_gear::GetMaterialLocations > {
  static const char* value()
  {
    return "nist_gear/GetMaterialLocations";
  }

  static const char* value(const ::nist_gear::GetMaterialLocations&) { return value(); }
};


// service_traits::MD5Sum< ::nist_gear::GetMaterialLocationsRequest> should match
// service_traits::MD5Sum< ::nist_gear::GetMaterialLocations >
template<>
struct MD5Sum< ::nist_gear::GetMaterialLocationsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nist_gear::GetMaterialLocations >::value();
  }
  static const char* value(const ::nist_gear::GetMaterialLocationsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nist_gear::GetMaterialLocationsRequest> should match
// service_traits::DataType< ::nist_gear::GetMaterialLocations >
template<>
struct DataType< ::nist_gear::GetMaterialLocationsRequest>
{
  static const char* value()
  {
    return DataType< ::nist_gear::GetMaterialLocations >::value();
  }
  static const char* value(const ::nist_gear::GetMaterialLocationsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nist_gear::GetMaterialLocationsResponse> should match
// service_traits::MD5Sum< ::nist_gear::GetMaterialLocations >
template<>
struct MD5Sum< ::nist_gear::GetMaterialLocationsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nist_gear::GetMaterialLocations >::value();
  }
  static const char* value(const ::nist_gear::GetMaterialLocationsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nist_gear::GetMaterialLocationsResponse> should match
// service_traits::DataType< ::nist_gear::GetMaterialLocations >
template<>
struct DataType< ::nist_gear::GetMaterialLocationsResponse>
{
  static const char* value()
  {
    return DataType< ::nist_gear::GetMaterialLocations >::value();
  }
  static const char* value(const ::nist_gear::GetMaterialLocationsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NIST_GEAR_MESSAGE_GETMATERIALLOCATIONS_H
