// Generated by gencpp from file nist_gear/PopulationControl.msg
// DO NOT EDIT!


#ifndef NIST_GEAR_MESSAGE_POPULATIONCONTROL_H
#define NIST_GEAR_MESSAGE_POPULATIONCONTROL_H

#include <ros/service_traits.h>


#include <nist_gear/PopulationControlRequest.h>
#include <nist_gear/PopulationControlResponse.h>


namespace nist_gear
{

struct PopulationControl
{

typedef PopulationControlRequest Request;
typedef PopulationControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PopulationControl
} // namespace nist_gear


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nist_gear::PopulationControl > {
  static const char* value()
  {
    return "02058b7d55716526fae62eb68abd6f31";
  }

  static const char* value(const ::nist_gear::PopulationControl&) { return value(); }
};

template<>
struct DataType< ::nist_gear::PopulationControl > {
  static const char* value()
  {
    return "nist_gear/PopulationControl";
  }

  static const char* value(const ::nist_gear::PopulationControl&) { return value(); }
};


// service_traits::MD5Sum< ::nist_gear::PopulationControlRequest> should match
// service_traits::MD5Sum< ::nist_gear::PopulationControl >
template<>
struct MD5Sum< ::nist_gear::PopulationControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nist_gear::PopulationControl >::value();
  }
  static const char* value(const ::nist_gear::PopulationControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nist_gear::PopulationControlRequest> should match
// service_traits::DataType< ::nist_gear::PopulationControl >
template<>
struct DataType< ::nist_gear::PopulationControlRequest>
{
  static const char* value()
  {
    return DataType< ::nist_gear::PopulationControl >::value();
  }
  static const char* value(const ::nist_gear::PopulationControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nist_gear::PopulationControlResponse> should match
// service_traits::MD5Sum< ::nist_gear::PopulationControl >
template<>
struct MD5Sum< ::nist_gear::PopulationControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nist_gear::PopulationControl >::value();
  }
  static const char* value(const ::nist_gear::PopulationControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nist_gear::PopulationControlResponse> should match
// service_traits::DataType< ::nist_gear::PopulationControl >
template<>
struct DataType< ::nist_gear::PopulationControlResponse>
{
  static const char* value()
  {
    return DataType< ::nist_gear::PopulationControl >::value();
  }
  static const char* value(const ::nist_gear::PopulationControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NIST_GEAR_MESSAGE_POPULATIONCONTROL_H
