// Generated by gencpp from file nist_gear/PopulationControlRequest.msg
// DO NOT EDIT!


#ifndef NIST_GEAR_MESSAGE_POPULATIONCONTROLREQUEST_H
#define NIST_GEAR_MESSAGE_POPULATIONCONTROLREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nist_gear
{
template <class ContainerAllocator>
struct PopulationControlRequest_
{
  typedef PopulationControlRequest_<ContainerAllocator> Type;

  PopulationControlRequest_()
    : action()  {
    }
  PopulationControlRequest_(const ContainerAllocator& _alloc)
    : action(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _action_type;
  _action_type action;





  typedef boost::shared_ptr< ::nist_gear::PopulationControlRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nist_gear::PopulationControlRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PopulationControlRequest_

typedef ::nist_gear::PopulationControlRequest_<std::allocator<void> > PopulationControlRequest;

typedef boost::shared_ptr< ::nist_gear::PopulationControlRequest > PopulationControlRequestPtr;
typedef boost::shared_ptr< ::nist_gear::PopulationControlRequest const> PopulationControlRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nist_gear::PopulationControlRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nist_gear::PopulationControlRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nist_gear::PopulationControlRequest_<ContainerAllocator1> & lhs, const ::nist_gear::PopulationControlRequest_<ContainerAllocator2> & rhs)
{
  return lhs.action == rhs.action;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nist_gear::PopulationControlRequest_<ContainerAllocator1> & lhs, const ::nist_gear::PopulationControlRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nist_gear

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::nist_gear::PopulationControlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nist_gear::PopulationControlRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nist_gear::PopulationControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nist_gear::PopulationControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nist_gear::PopulationControlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nist_gear::PopulationControlRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nist_gear::PopulationControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7757aad79fa343e61bc69ed7f1b7666d";
  }

  static const char* value(const ::nist_gear::PopulationControlRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7757aad79fa343e6ULL;
  static const uint64_t static_value2 = 0x1bc69ed7f1b7666dULL;
};

template<class ContainerAllocator>
struct DataType< ::nist_gear::PopulationControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nist_gear/PopulationControlRequest";
  }

  static const char* value(const ::nist_gear::PopulationControlRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nist_gear::PopulationControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Population control\n"
"\n"
"# desired action: \"pause\", \"resume\" or \"restart\"\n"
"string action\n"
"\n"
;
  }

  static const char* value(const ::nist_gear::PopulationControlRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nist_gear::PopulationControlRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PopulationControlRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nist_gear::PopulationControlRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nist_gear::PopulationControlRequest_<ContainerAllocator>& v)
  {
    s << indent << "action: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.action);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIST_GEAR_MESSAGE_POPULATIONCONTROLREQUEST_H
