// Generated by gencpp from file nist_gear/VacuumGripperControlRequest.msg
// DO NOT EDIT!


#ifndef NIST_GEAR_MESSAGE_VACUUMGRIPPERCONTROLREQUEST_H
#define NIST_GEAR_MESSAGE_VACUUMGRIPPERCONTROLREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nist_gear
{
template <class ContainerAllocator>
struct VacuumGripperControlRequest_
{
  typedef VacuumGripperControlRequest_<ContainerAllocator> Type;

  VacuumGripperControlRequest_()
    : enable(false)  {
    }
  VacuumGripperControlRequest_(const ContainerAllocator& _alloc)
    : enable(false)  {
  (void)_alloc;
    }



   typedef uint8_t _enable_type;
  _enable_type enable;





  typedef boost::shared_ptr< ::nist_gear::VacuumGripperControlRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nist_gear::VacuumGripperControlRequest_<ContainerAllocator> const> ConstPtr;

}; // struct VacuumGripperControlRequest_

typedef ::nist_gear::VacuumGripperControlRequest_<std::allocator<void> > VacuumGripperControlRequest;

typedef boost::shared_ptr< ::nist_gear::VacuumGripperControlRequest > VacuumGripperControlRequestPtr;
typedef boost::shared_ptr< ::nist_gear::VacuumGripperControlRequest const> VacuumGripperControlRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nist_gear::VacuumGripperControlRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nist_gear::VacuumGripperControlRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nist_gear::VacuumGripperControlRequest_<ContainerAllocator1> & lhs, const ::nist_gear::VacuumGripperControlRequest_<ContainerAllocator2> & rhs)
{
  return lhs.enable == rhs.enable;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nist_gear::VacuumGripperControlRequest_<ContainerAllocator1> & lhs, const ::nist_gear::VacuumGripperControlRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nist_gear

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::nist_gear::VacuumGripperControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nist_gear::VacuumGripperControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nist_gear::VacuumGripperControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nist_gear::VacuumGripperControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nist_gear::VacuumGripperControlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nist_gear::VacuumGripperControlRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nist_gear::VacuumGripperControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8c1211af706069c994c06e00eb59ac9e";
  }

  static const char* value(const ::nist_gear::VacuumGripperControlRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8c1211af706069c9ULL;
  static const uint64_t static_value2 = 0x94c06e00eb59ac9eULL;
};

template<class ContainerAllocator>
struct DataType< ::nist_gear::VacuumGripperControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nist_gear/VacuumGripperControlRequest";
  }

  static const char* value(const ::nist_gear::VacuumGripperControlRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nist_gear::VacuumGripperControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Vacuum gripper control\n"
"\n"
"# Enable/Disable gripper suction\n"
"bool enable\n"
"\n"
;
  }

  static const char* value(const ::nist_gear::VacuumGripperControlRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nist_gear::VacuumGripperControlRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.enable);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VacuumGripperControlRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nist_gear::VacuumGripperControlRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nist_gear::VacuumGripperControlRequest_<ContainerAllocator>& v)
  {
    s << indent << "enable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enable);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIST_GEAR_MESSAGE_VACUUMGRIPPERCONTROLREQUEST_H
